#!/bin/sh

if [ ! "`php /app/owncloud/occ config:system:get installed`" == "false" ]; then 
 echo "configuranding owncloud"
 cd /app/owncloud
 echo  -n "wait db ";
 while 	! nc -z -w 4 db 3306; do
	echo -n ".";
	sleep 1;
 done
 
 echo " ready";

 chown root /app/owncloud/config/config.php

 php occ  maintenance:install \
	--database "mysql" \
	--database-host "db" \
	--database-name "owncloud" \
	--database-user "root" \
	--database-pass "" \
	--admin-user "admin" \
	--admin-pass "secret" \
	--data-dir=/app/owncloud/data

 php occ upgrade
 php occ app:disable gallery
 php occ app:enable galleryplus
 php occ app:enable documents
 php occ config:system:set defaultapp --value=activity
 php occ config:system:set trusted_domain --value=127.0.0.1
 php occ config:system:set filelocking.enabled --value='true'
 php occ config:system:set memcache.local --value='\OC\Memcache\APCu'

fi

touch /var/log/httpd/access_log
touch /var/log/httpd/error_log
tail -f /var/log/httpd/* &
rm -f /run/httpd/httpd.pid
httpd -D FOREGROUND
